# Site Information
site_name: ''
site_url: https://atditto.github.io/
site_author: atditto
# Repository Information
repo_name: atditto/@ã€ƒ
repo_url: https://github.com/atditto/atditto.github.io

# Navigation Config
nav:
  - ğŸ  ä¸»é¡µ:
      - index.md
      - about.md

# Theme Config
theme:
  name: material
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
    logo: octicons/command-palette-16
  palette:
    - media: "(prefers-color-scheme: light)"  # ç›‘å¬æ“ä½œç³»ç»Ÿæ˜¯å¦è®¾ç½®ä¸ºæµ…è‰²ä¸»é¢˜
      scheme: default                        # ä½¿ç”¨ Material çš„é»˜è®¤è‰²å½©æ–¹æ¡ˆï¼ˆäº®è‰²èƒŒæ™¯ï¼‰
      primary: cyan                          # ä¸»è‰²è°ƒï¼šåº”ç”¨äºé¡¶éƒ¨å¯¼èˆªæ ã€æŒ‰é’®ç­‰
      accent: blue                           # å¼ºè°ƒè‰²ï¼šç”¨äºé“¾æ¥ã€é€‰ä¸­çŠ¶æ€ã€æ»‘å—ç­‰äº¤äº’å…ƒç´ 
      toggle:
        icon: octicons/moon-16         # åˆ‡æ¢æŒ‰é’®å›¾æ ‡ï¼šæ˜¾ç¤ºä¸ºâ€œå¼€â€çŠ¶æ€çš„å¼€å…³
        name: åˆ‡æ¢åˆ°å¤œé—´æ¨¡å¼                # é¼ æ ‡æ‚¬åœæ—¶æ˜¾ç¤ºçš„æç¤ºæ–‡å­—

    - media: "(prefers-color-scheme: dark)"  # ç›‘å¬æ“ä½œç³»ç»Ÿæ˜¯å¦è®¾ç½®ä¸ºæ·±è‰²ä¸»é¢˜
      scheme: slate                          # ä½¿ç”¨ Material çš„æ·±è‰²æ–¹æ¡ˆï¼ˆæ·±ç°èƒŒæ™¯ï¼ŒæŠ¤çœ¼ï¼‰
      primary: black                         # ä¸»è‰²è°ƒï¼šé¡¶éƒ¨å¯¼èˆªæ å˜ä¸ºé»‘è‰²ï¼Œæ›´æ²‰æµ¸
      accent: indigo                         # å¼ºè°ƒè‰²ï¼šé›è“è‰²ï¼Œä¸æ·±è‰²èƒŒæ™¯æ­é…æ›´åè°ƒ
      toggle:
        icon: octicons/sun-16  # åˆ‡æ¢æŒ‰é’®å›¾æ ‡ï¼šæ˜¾ç¤ºä¸ºâ€œå…³â€çŠ¶æ€çš„å¼€å…³
        name: åˆ‡æ¢åˆ°æ—¥é—´æ¨¡å¼                # é¼ æ ‡æ‚¬åœæ—¶æ˜¾ç¤ºçš„æç¤ºæ–‡å­—

  features:
    - announce.dismiss #å‘ˆç°å¯æ ‡è®°ä¸ºç”±ç”¨æˆ·è¯»å–çš„ä¸´æ—¶å…¬å‘Šï¼Œå¯ä»¥åŒ…å«ä¸€ä¸ªç”¨äºå–æ¶ˆå½“å‰å…¬å‘Šçš„æŒ‰é’®
    # - navigation.instant
    #- header.autohide  #è‡ªåŠ¨éšè—
    - navigation.tracking #åœ°å€æ ä¸­çš„ URL å°†è‡ªåŠ¨æ›´æ–°ä¸ºåœ¨ç›®å½•ä¸­çªå‡ºæ˜¾ç¤ºçš„æ´»åŠ¨é”šç‚¹
    - navigation.tabs #é¡¶çº§éƒ¨åˆ†å°†å‘ˆç°åœ¨ä¸Šé¢è§†å£æ ‡é¢˜ä¸‹æ–¹çš„èœå•å±‚ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    # - navigation.tabs.sticky  #å¯ç”¨ç²˜æ€§é€‰é¡¹å¡åï¼Œå¯¼èˆªé€‰é¡¹å¡å°†é”å®šåœ¨æ ‡é¢˜ä¸‹æ–¹ï¼Œå¹¶åœ¨å‘ä¸‹æ»šåŠ¨æ—¶å§‹ç»ˆä¿æŒå¯è§
    - navigation.sections #å¯ç”¨éƒ¨åˆ†åï¼Œé¡¶çº§éƒ¨åˆ†åœ¨è¾¹æ ä¸­å‘ˆç°ä¸º1220pxä»¥ä¸Šè§†å£çš„ç»„ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.footer #é¡µè„šå°†å‘ˆç°åœ¨è¾¹æ ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - search.share #æœç´¢åˆ†äº«æŒ‰é’®
    - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - navigation.indexes #å¯ç”¨èŠ‚ç´¢å¼•é¡µåï¼Œå¯ä»¥å°†æ–‡æ¡£ç›´æ¥é™„åŠ åˆ°èŠ‚
    - content.tabs.link
    - content.tooltips
    - content.code.copy #ä»£ç å¤åˆ¶
    - content.action.edit
    - content.action.view
    - content.code.annotate


