# Site Information
site_name: ''
site_url: https://atditto.github.io/
site_author: atditto
# Repository Information
repo_name: atditto/@ã€ƒ
repo_url: https://github.com/atditto/atditto.github.io

# Navigation Config
nav:
  - ğŸ  ä¸»é¡µ: index.md
  - ğŸ‘­ å‹é“¾: links.md
  - ğŸ“– ç¬”è®°:
      - note/index.md
      - "MIT Web Lab(6.962)":
          - note/6.962/index.md
          - note/6.962/day1.md


# Theme Config
theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    logo: octicons/command-palette-16
  palette:
    # å¤œé—´æ¨¡å¼ä½œä¸ºé»˜è®¤ä¸»é¢˜ï¼ˆæ”¾åœ¨ç¬¬ä¸€ä½ï¼‰
    - scheme: slate                          # æ·±è‰²ä¸»é¢˜
      primary: black                         # ä¸»è‰²è°ƒï¼šé»‘è‰²
      accent: indigo                         # å¼ºè°ƒè‰²ï¼šé›è“è‰²
      toggle:
        icon: octicons/sun-16                # å›¾æ ‡æ˜¾ç¤ºä¸ºå¤ªé˜³ï¼ˆè¡¨ç¤ºå½“å‰æ˜¯å¤œé—´ï¼Œç‚¹å‡»åˆ‡æ¢åˆ°æ—¥é—´ï¼‰
        name: åˆ‡æ¢åˆ°æ—¥é—´æ¨¡å¼                  # æç¤ºæ–‡å­—

    # æ—¥é—´æ¨¡å¼ä½œä¸ºå¤‡é€‰
    - scheme: default                        # æµ…è‰²ä¸»é¢˜
      primary: cyan                          # ä¸»è‰²è°ƒï¼šé’è‰²
      accent: blue                           # å¼ºè°ƒè‰²ï¼šè“è‰²
      toggle:
        icon: octicons/moon-16               # å›¾æ ‡æ˜¾ç¤ºä¸ºæœˆäº®ï¼ˆè¡¨ç¤ºå½“å‰æ˜¯æ—¥é—´ï¼Œç‚¹å‡»åˆ‡æ¢åˆ°å¤œé—´ï¼‰
        name: åˆ‡æ¢åˆ°å¤œé—´æ¨¡å¼                  # æç¤ºæ–‡å­—

  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.instant # This will cause LaTeX render fail at the first try.
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    # - navigation.prune


