site_name: '@〃'
site_url: https://atditto.github.io/
site_author: atditto
# Repository
repo_name: atditto/@〃
repo_url: https://github.com/atditto/atditto.github.io

nav:
  - 主页:
      - index.md


theme:
  name: material
  language: zh # 一些提示性的文字会变成中文
  palette:
    # ===================================================================
    # 日间模式：当用户系统设置为“浅色模式”时自动启用
    # ===================================================================
    - media: "(prefers-color-scheme: light)"  # 监听操作系统是否设置为浅色主题
      scheme: default                        # 使用 Material 的默认色彩方案（亮色背景）
      primary: cyan                          # 主色调：应用于顶部导航栏、按钮等
      accent: blue                           # 强调色：用于链接、选中状态、滑块等交互元素
      toggle:
        icon: octicons/moon-16         # 切换按钮图标：显示为“开”状态的开关
        name: 切换到夜间模式                # 鼠标悬停时显示的提示文字

    # ===================================================================
    # 夜间模式：当用户系统设置为“深色模式”时自动启用
    # ===================================================================
    - media: "(prefers-color-scheme: dark)"  # 监听操作系统是否设置为深色主题
      scheme: slate                          # 使用 Material 的深色方案（深灰背景，护眼）
      primary: black                         # 主色调：顶部导航栏变为黑色，更沉浸
      accent: indigo                         # 强调色：靛蓝色，与深色背景搭配更协调
      toggle:
        icon: octicons/sun-16  # 切换按钮图标：显示为“关”状态的开关
        name: 切换到日间模式                # 鼠标悬停时显示的提示文字

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate

  icon:
    logo: octicons/command-palette-16
