# Site Information
site_name: ''
site_url: https://atditto.github.io/
site_author: atditto
# Repository Information
repo_name: atditto/@ã€ƒ
repo_url: https://github.com/atditto/atditto.github.io

# Navigation Config
nav:
  - ğŸ  ä¸»é¡µ: index.md
  - ğŸ‘­ å‹é“¾: links.md
  - ğŸ“– ç¬”è®°: note/test.md

# Theme Config
theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    logo: octicons/command-palette-16
  palette:
    # - media: "(prefers-color-scheme: light)"  # ç›‘å¬æ“ä½œç³»ç»Ÿæ˜¯å¦è®¾ç½®ä¸ºæµ…è‰²ä¸»é¢˜
    #   scheme: default                        # ä½¿ç”¨ Material çš„é»˜è®¤è‰²å½©æ–¹æ¡ˆï¼ˆäº®è‰²èƒŒæ™¯ï¼‰
    #   primary: cyan                          # ä¸»è‰²è°ƒï¼šåº”ç”¨äºé¡¶éƒ¨å¯¼èˆªæ ã€æŒ‰é’®ç­‰
    #   accent: blue                           # å¼ºè°ƒè‰²ï¼šç”¨äºé“¾æ¥ã€é€‰ä¸­çŠ¶æ€ã€æ»‘å—ç­‰äº¤äº’å…ƒç´ 
    #   toggle:
    #     icon: octicons/moon-16         # åˆ‡æ¢æŒ‰é’®å›¾æ ‡ï¼šæ˜¾ç¤ºä¸ºâ€œå¼€â€çŠ¶æ€çš„å¼€å…³
    #     name: åˆ‡æ¢åˆ°å¤œé—´æ¨¡å¼                # é¼ æ ‡æ‚¬åœæ—¶æ˜¾ç¤ºçš„æç¤ºæ–‡å­—

    - media: "(prefers-color-scheme: dark)"  # ç›‘å¬æ“ä½œç³»ç»Ÿæ˜¯å¦è®¾ç½®ä¸ºæ·±è‰²ä¸»é¢˜
      scheme: slate                          # ä½¿ç”¨ Material çš„æ·±è‰²æ–¹æ¡ˆï¼ˆæ·±ç°èƒŒæ™¯ï¼ŒæŠ¤çœ¼ï¼‰
      primary: black                         # ä¸»è‰²è°ƒï¼šé¡¶éƒ¨å¯¼èˆªæ å˜ä¸ºé»‘è‰²ï¼Œæ›´æ²‰æµ¸
      accent: indigo                         # å¼ºè°ƒè‰²ï¼šé›è“è‰²ï¼Œä¸æ·±è‰²èƒŒæ™¯æ­é…æ›´åè°ƒ
      toggle:
        icon: octicons/sun-16  # åˆ‡æ¢æŒ‰é’®å›¾æ ‡ï¼šæ˜¾ç¤ºä¸ºâ€œå…³â€çŠ¶æ€çš„å¼€å…³
        name: åˆ‡æ¢åˆ°æ—¥é—´æ¨¡å¼                # é¼ æ ‡æ‚¬åœæ—¶æ˜¾ç¤ºçš„æç¤ºæ–‡å­—

  features:
    - content.code.annotate
    - content.code.copy
    # - navigation.instant # This will cause LaTeX render fail at the first try.
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    # - navigation.prune


